/*
 * Formula D
 * Simple API for a Formula D AI server.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.relex.model.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Gear of the car. It can be be 0 in the start but 0 can never be chosen.
 */
@ApiModel(description = "Gear of the car. It can be be 0 in the start but 0 can never be chosen.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-13T23:19:30.736+03:00")
public class Gear {
  @SerializedName("gear")
  private Integer gear = null;

  public Gear gear(Integer gear) {
    this.gear = gear;
    return this;
  }

   /**
   * Get gear
   * @return gear
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getGear() {
    return gear;
  }

  public void setGear(Integer gear) {
    this.gear = gear;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Gear gear = (Gear) o;
    return Objects.equals(this.gear, gear.gear);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gear);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Gear {\n");
    
    sb.append("    gear: ").append(toIndentedString(gear)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

