/*
 * Formula D
 * Simple API for a Formula D AI server.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.relex.model.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fi.relex.model.model.GameId;
import fi.relex.model.model.InitializeTrack;
import fi.relex.model.model.PlayerId;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Track
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-13T23:19:30.736+03:00")
public class Track {
  @SerializedName("player")
  private PlayerId player = null;

  @SerializedName("game")
  private GameId game = null;

  @SerializedName("track")
  private InitializeTrack track = null;

  public Track player(PlayerId player) {
    this.player = player;
    return this;
  }

   /**
   * Get player
   * @return player
  **/
  @ApiModelProperty(required = true, value = "")
  public PlayerId getPlayer() {
    return player;
  }

  public void setPlayer(PlayerId player) {
    this.player = player;
  }

  public Track game(GameId game) {
    this.game = game;
    return this;
  }

   /**
   * Get game
   * @return game
  **/
  @ApiModelProperty(required = true, value = "")
  public GameId getGame() {
    return game;
  }

  public void setGame(GameId game) {
    this.game = game;
  }

  public Track track(InitializeTrack track) {
    this.track = track;
    return this;
  }

   /**
   * Get track
   * @return track
  **/
  @ApiModelProperty(required = true, value = "")
  public InitializeTrack getTrack() {
    return track;
  }

  public void setTrack(InitializeTrack track) {
    this.track = track;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Track track = (Track) o;
    return Objects.equals(this.player, track.player) &&
        Objects.equals(this.game, track.game) &&
        Objects.equals(this.track, track.track);
  }

  @Override
  public int hashCode() {
    return Objects.hash(player, game, track);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Track {\n");
    
    sb.append("    player: ").append(toIndentedString(player)).append("\n");
    sb.append("    game: ").append(toIndentedString(game)).append("\n");
    sb.append("    track: ").append(toIndentedString(track)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

